## NUMPY: ARRAYS AND MATRICES

In [2]:
# importing required modules
import numpy as np

### Create Arrays

In [14]:
# create ndarray from a tuple
data1 = (1, 2, 3, 4, 5, 6, 7, 8)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))   # (8,) denotes singleton notation, means tuple with single data item

(1, 2, 3, 4, 5, 6, 7, 8) 8 <class 'tuple'> 2401509330048
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401508721264


In [17]:
# create ndarray from a list
data1 = [1, 2, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401518461888
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401508724528
[1, 2, 3, 4, 5, 6, 7, 8]


In [117]:
# create ndarray from a list
data1 = [1, 2.0, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2.0, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401524781696
[1. 2. 3. 4. 5. 6. 7. 8.] 8 (8,) <class 'numpy.ndarray'> 2401529838832
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


In [118]:
# create ndarray from a list
data1 = [1, 2, '3.0', 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, '3.0', 4, 5, 6, 7, 8] 8 <class 'list'> 2401524745344
['1' '2' '3.0' '4' '5' '6' '7' '8'] 8 (8,) <class 'numpy.ndarray'> 2401515105616
['1', '2', '3.0', '4', '5', '6', '7', '8']


In [120]:
# create ndarray from a list
data1 = [1, 2, 3, True, 5, 6, False, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, True, 5, 6, False, 8] 8 <class 'list'> 2401524284224
[1 2 3 1 5 6 0 8] 8 (8,) <class 'numpy.ndarray'> 2401525105456
[1, 2, 3, 1, 5, 6, 0, 8]


In [121]:
# create ndarray from a list
data1 = [1, 2, 3, True, 5.5, '6', 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, True, 5.5, '6', 7, 8] 8 <class 'list'> 2401518104384
['1' '2' '3' 'True' '5.5' '6' '7' '8'] 8 (8,) <class 'numpy.ndarray'> 2401525105936
['1', '2', '3', 'True', '5.5', '6', '7', '8']


In [12]:
data2 = range(1,5)
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))

range(1, 5) [1, 2, 3, 4] 4 <class 'range'> 2401508636784
[1 2 3 4] 4 (4,) <class 'numpy.ndarray'> 2401508724528


In [11]:
data2 = [range(1,5), range(5, 9)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))

[range(1, 5), range(5, 9)] [range(1, 5), range(5, 9)] 2 <class 'list'> 2401508453376
[[1 2 3 4]
 [5 6 7 8]] 2 (2, 4) <class 'numpy.ndarray'> 2401508724144


In [16]:
data2 = [range(1,5), range(5, 9), range(9, 13)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))
print (arr2.tolist())

[range(1, 5), range(5, 9), range(9, 13)] [range(1, 5), range(5, 9), range(9, 13)] 3 <class 'list'> 2401512168832
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3 (3, 4) <class 'numpy.ndarray'> 2401513473104
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [23]:
# examining arrays
data1 = [1, 2, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.dtype, arr1.ndim, arr1.shape, arr1.size, len(arr1))

[1, 2, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401515526976
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401519190544
int32 1 (8,) 8 8


In [24]:
data2 = [range(1,5), range(5, 9), range(9, 13)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))
print (arr2.dtype, arr2.ndim, arr2.shape, arr2.size, len(arr2))

[range(1, 5), range(5, 9), range(9, 13)] [range(1, 5), range(5, 9), range(9, 13)] 3 <class 'list'> 2401515416000
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3 (3, 4) <class 'numpy.ndarray'> 2401519194000
int32 2 (3, 4) 12 3


In [36]:
# create special arrays
print (np.zeros(12))
print (np.zeros(12).astype(int))
print (np.zeros(12).astype(str))
print (np.zeros(12).astype(int).reshape(3, 4))
print (np.zeros(12).reshape(3, 4))
print (np.zeros(12).reshape(3, 4).astype(int))
print (np.zeros(24).reshape(2, 3, 4))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]
['0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0']
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [37]:
print (np.ones(12))
print (np.ones(12).astype(int))
print (np.ones(12).astype(str))
print (np.ones(12).astype(int).reshape(3, 4))
print (np.ones(12).reshape(3, 4))
print (np.ones(12).reshape(3, 4).astype(int))
print (np.ones(24).reshape(2, 3, 4))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1]
['1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0']
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [42]:
list1 = np.zeros(20)
print (list1)
list1 = np.zeros(20).reshape(5, 4)
print (list1)
list1 = np.zeros(20).reshape(5, 4).astype(int)
print (list1)
list1 = np.zeros(20).reshape(5, 4).astype(int).tolist()
print (list1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [45]:
print (np.linspace(0, 1, 5))
print (np.linspace(0, 10, 11))
print (np.linspace(0, 10, 21))

[0.   0.25 0.5  0.75 1.  ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [48]:
print (np.linspace(0, 3, 4))
print (np.logspace(0, 3, 4))
print (np.logspace(0, 3, 4).astype(int))

[0. 1. 2. 3.]
[   1.   10.  100. 1000.]
[   1   10  100 1000]


In [59]:
# slicing and indexing
data1 = [11, 22, 33, 44, 55, 66, 77, 88]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1[4], arr1[-4], arr1[6], arr1[-2])      # indexing
print (arr1[2: 6], arr1[-6: -2], arr1[2: -2], arr1[-6: 6])
print (arr1[5: 2: -1], arr1[-3: -6: -1], arr1[5: -6: -1], arr1[-3: 2: -1])
print (arr1[::2], arr1[1::2])

[11, 22, 33, 44, 55, 66, 77, 88] 8 <class 'list'> 2401518246848
[11 22 33 44 55 66 77 88] 8 (8,) <class 'numpy.ndarray'> 2401526754256
55 55 77 77
[33 44 55 66] [33 44 55 66] [33 44 55 66] [33 44 55 66]
[66 55 44] [66 55 44] [66 55 44] [66 55 44]
[11 33 55 77] [22 44 66 88]


In [74]:
data1 = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1).reshape(3, 4)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1[2, 1], arr1[2][1], arr1[-1, -3], arr1[-1][-3])
print (arr1[:, 1:3])
print (arr1[0:2, :])

[11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333] 12 <class 'list'> 2401524622208
[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]] 3 (3, 4) <class 'numpy.ndarray'> 2401525106224
111 111 111 111
[[ 22  33]
 [ 66  77]
 [111 222]]
[[11 22 33 44]
 [55 66 77 88]]


In [77]:
print (arr1[0:2,1:3])
print (arr1[:2,1:3])
print (arr1[:-1, -3: -1])

[[22 33]
 [66 77]]
[[22 33]
 [66 77]]
[[22 33]
 [66 77]]


In [85]:
# views and copies
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 50
print (arr)
arr_view = arr[5:8]        # referring same instance
print (arr_view)
arr_view[:] = 100
print (arr_view)
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 50 50 50  8  9]
[50 50 50]
[100 100 100]
[  0   1   2   3   4 100 100 100   8   9]


In [86]:
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 50
print (arr)
arr_view = arr[5:8].copy()   # referring separate instance
print (arr_view)
arr_view[:] = 100
print (arr_view)
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 50 50 50  8  9]
[50 50 50]
[100 100 100]
[ 0  1  2  3  4 50 50 50  8  9]


In [98]:
# using boolean arrays
arr = np.arange(0, 10)
print (arr)
print (arr > 5)
print (~(arr > 5))
print (arr[arr > 5])
print (True, not True, False, not False)
print (arr[~(arr > 5)])
arr[arr > 5] = 100
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[ True  True  True  True  True  True False False False False]
[6 7 8 9]
True False False True
[0 1 2 3 4 5]
[  0   1   2   3   4   5 100 100 100 100]


In [106]:
arr = np.arange(0, 10)
print (arr)
print ((arr > 3) & (arr < 8))
print (arr[(arr > 3) & (arr < 8)])
print ((arr < 3) | (arr > 8))
print (arr[(arr < 3) | (arr > 8)])

[0 1 2 3 4 5 6 7 8 9]
[False False False False  True  True  True  True False False]
[4 5 6 7]
[ True  True  True False False False False False False  True]
[0 1 2 9]


In [111]:
arr = np.arange(0, 10)
print (arr)
print (arr % 2 == 0)
print (arr[arr % 2 == 0])
print (arr[arr % 2 == 1])
print (arr[arr % 2 != 0])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5 7 9]


In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names, type(names))
print (names == 'Bob')
print (names == 'bob')
print (names != 'Bob')
print (names[names != 'Bob'])
print ((names == 'Bob') | (names == 'Joe'))
print (names[(names == 'Bob') | (names == 'Joe')])
names[names == 'Bob'] = 'Tom'
print (names)

['Bob' 'Joe' 'Will' 'Bob'] <class 'numpy.ndarray'>
[ True False False  True]
[False False False False]
[False  True  True False]
['Joe' 'Will']
[ True  True False  True]
['Bob' 'Joe' 'Bob']
['Tom' 'Joe' 'Will' 'Tom']


In [129]:
names = np.array(['Bob', 'Joe', 'Will', 'Will', 'Joe', 'Bob', 'Bob'])
print (names, type(names))
print (np.unique(names))

['Bob' 'Joe' 'Will' 'Will' 'Joe' 'Bob' 'Bob'] <class 'numpy.ndarray'>
['Bob' 'Joe' 'Will']


### Vectorized Operations

In [135]:
nums = np.arange(10)
print (nums, type(nums))
print (list(nums), type(list(nums)), nums.tolist(), type(nums.tolist()))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [148]:
import math
nums = np.arange(10)
print (nums, type(nums))
print (nums * 100)    # vector * scalar operation
print (nums * np.array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100]))    # vector * vector operation
print (np.sqrt(nums), math.sqrt(100), np.sqrt(100))     # Error !!! for math.sqrt(nums))
print (np.sqrt(nums))
print (np.ceil(np.sqrt(nums)))
print (np.floor(np.sqrt(nums)))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[  0 100 200 300 400 500 600 700 800 900]
[  0 100 200 300 400 500 600 700 800 900]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 10.0 10.0
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 1. 2. 2. 2. 3. 3. 3. 3. 3.]
[0. 1. 1. 1. 2. 2. 2. 2. 2. 3.]
