## NUMPY: ARRAYS AND MATRICES

In [2]:
# importing required modules
import numpy as np

### Create Arrays

In [14]:
# create ndarray from a tuple
data1 = (1, 2, 3, 4, 5, 6, 7, 8)
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))   # (8,) denotes singleton notation, means tuple with single data item

(1, 2, 3, 4, 5, 6, 7, 8) 8 <class 'tuple'> 2401509330048
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401508721264


In [17]:
# create ndarray from a list
data1 = [1, 2, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401518461888
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401508724528
[1, 2, 3, 4, 5, 6, 7, 8]


In [117]:
# create ndarray from a list
data1 = [1, 2.0, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2.0, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401524781696
[1. 2. 3. 4. 5. 6. 7. 8.] 8 (8,) <class 'numpy.ndarray'> 2401529838832
[1.0, 2.0, 3.0, 4.0, 5.0, 6.0, 7.0, 8.0]


In [118]:
# create ndarray from a list
data1 = [1, 2, '3.0', 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, '3.0', 4, 5, 6, 7, 8] 8 <class 'list'> 2401524745344
['1' '2' '3.0' '4' '5' '6' '7' '8'] 8 (8,) <class 'numpy.ndarray'> 2401515105616
['1', '2', '3.0', '4', '5', '6', '7', '8']


In [120]:
# create ndarray from a list
data1 = [1, 2, 3, True, 5, 6, False, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, True, 5, 6, False, 8] 8 <class 'list'> 2401524284224
[1 2 3 1 5 6 0 8] 8 (8,) <class 'numpy.ndarray'> 2401525105456
[1, 2, 3, 1, 5, 6, 0, 8]


In [121]:
# create ndarray from a list
data1 = [1, 2, 3, True, 5.5, '6', 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.tolist())

[1, 2, 3, True, 5.5, '6', 7, 8] 8 <class 'list'> 2401518104384
['1' '2' '3' 'True' '5.5' '6' '7' '8'] 8 (8,) <class 'numpy.ndarray'> 2401525105936
['1', '2', '3', 'True', '5.5', '6', '7', '8']


In [12]:
data2 = range(1,5)
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))

range(1, 5) [1, 2, 3, 4] 4 <class 'range'> 2401508636784
[1 2 3 4] 4 (4,) <class 'numpy.ndarray'> 2401508724528


In [11]:
data2 = [range(1,5), range(5, 9)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))

[range(1, 5), range(5, 9)] [range(1, 5), range(5, 9)] 2 <class 'list'> 2401508453376
[[1 2 3 4]
 [5 6 7 8]] 2 (2, 4) <class 'numpy.ndarray'> 2401508724144


In [16]:
data2 = [range(1,5), range(5, 9), range(9, 13)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))
print (arr2.tolist())

[range(1, 5), range(5, 9), range(9, 13)] [range(1, 5), range(5, 9), range(9, 13)] 3 <class 'list'> 2401512168832
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3 (3, 4) <class 'numpy.ndarray'> 2401513473104
[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [23]:
# examining arrays
data1 = [1, 2, 3, 4, 5, 6, 7, 8]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1.dtype, arr1.ndim, arr1.shape, arr1.size, len(arr1))

[1, 2, 3, 4, 5, 6, 7, 8] 8 <class 'list'> 2401515526976
[1 2 3 4 5 6 7 8] 8 (8,) <class 'numpy.ndarray'> 2401519190544
int32 1 (8,) 8 8


In [24]:
data2 = [range(1,5), range(5, 9), range(9, 13)]
print (data2, list(data2), len(data2), type(data2), id(data2))
arr2 = np.array(data2)
print (arr2, len(arr2), arr2.shape, type(arr2), id(arr2))
print (arr2.dtype, arr2.ndim, arr2.shape, arr2.size, len(arr2))

[range(1, 5), range(5, 9), range(9, 13)] [range(1, 5), range(5, 9), range(9, 13)] 3 <class 'list'> 2401515416000
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 3 (3, 4) <class 'numpy.ndarray'> 2401519194000
int32 2 (3, 4) 12 3


In [36]:
# create special arrays
print (np.zeros(12))
print (np.zeros(12).astype(int))
print (np.zeros(12).astype(str))
print (np.zeros(12).astype(int).reshape(3, 4))
print (np.zeros(12).reshape(3, 4))
print (np.zeros(12).reshape(3, 4).astype(int))
print (np.zeros(24).reshape(2, 3, 4))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0 0 0]
['0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0' '0.0']
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [37]:
print (np.ones(12))
print (np.ones(12).astype(int))
print (np.ones(12).astype(str))
print (np.ones(12).astype(int).reshape(3, 4))
print (np.ones(12).reshape(3, 4))
print (np.ones(12).reshape(3, 4).astype(int))
print (np.ones(24).reshape(2, 3, 4))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1 1 1 1 1 1 1 1 1 1 1 1]
['1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0' '1.0']
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [42]:
list1 = np.zeros(20)
print (list1)
list1 = np.zeros(20).reshape(5, 4)
print (list1)
list1 = np.zeros(20).reshape(5, 4).astype(int)
print (list1)
list1 = np.zeros(20).reshape(5, 4).astype(int).tolist()
print (list1)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]


In [45]:
print (np.linspace(0, 1, 5))
print (np.linspace(0, 10, 11))
print (np.linspace(0, 10, 21))

[0.   0.25 0.5  0.75 1.  ]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
[ 0.   0.5  1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5
  7.   7.5  8.   8.5  9.   9.5 10. ]


In [48]:
print (np.linspace(0, 3, 4))
print (np.logspace(0, 3, 4))
print (np.logspace(0, 3, 4).astype(int))

[0. 1. 2. 3.]
[   1.   10.  100. 1000.]
[   1   10  100 1000]


In [59]:
# slicing and indexing
data1 = [11, 22, 33, 44, 55, 66, 77, 88]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1[4], arr1[-4], arr1[6], arr1[-2])      # indexing
print (arr1[2: 6], arr1[-6: -2], arr1[2: -2], arr1[-6: 6])
print (arr1[5: 2: -1], arr1[-3: -6: -1], arr1[5: -6: -1], arr1[-3: 2: -1])
print (arr1[::2], arr1[1::2])

[11, 22, 33, 44, 55, 66, 77, 88] 8 <class 'list'> 2401518246848
[11 22 33 44 55 66 77 88] 8 (8,) <class 'numpy.ndarray'> 2401526754256
55 55 77 77
[33 44 55 66] [33 44 55 66] [33 44 55 66] [33 44 55 66]
[66 55 44] [66 55 44] [66 55 44] [66 55 44]
[11 33 55 77] [22 44 66 88]


In [74]:
data1 = [11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333]
print (data1, len(data1), type(data1), id(data1))
arr1 = np.array(data1).reshape(3, 4)
print (arr1, len(arr1), arr1.shape, type(arr1), id(arr1))
print (arr1[2, 1], arr1[2][1], arr1[-1, -3], arr1[-1][-3])
print (arr1[:, 1:3])
print (arr1[0:2, :])

[11, 22, 33, 44, 55, 66, 77, 88, 99, 111, 222, 333] 12 <class 'list'> 2401524622208
[[ 11  22  33  44]
 [ 55  66  77  88]
 [ 99 111 222 333]] 3 (3, 4) <class 'numpy.ndarray'> 2401525106224
111 111 111 111
[[ 22  33]
 [ 66  77]
 [111 222]]
[[11 22 33 44]
 [55 66 77 88]]


In [77]:
print (arr1[0:2,1:3])
print (arr1[:2,1:3])
print (arr1[:-1, -3: -1])

[[22 33]
 [66 77]]
[[22 33]
 [66 77]]
[[22 33]
 [66 77]]


In [85]:
# views and copies
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 50
print (arr)
arr_view = arr[5:8]        # referring same instance
print (arr_view)
arr_view[:] = 100
print (arr_view)
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 50 50 50  8  9]
[50 50 50]
[100 100 100]
[  0   1   2   3   4 100 100 100   8   9]


In [86]:
arr = np.arange(10)
print (arr)
print (arr[5:8])
arr[5:8] = 50
print (arr)
arr_view = arr[5:8].copy()   # referring separate instance
print (arr_view)
arr_view[:] = 100
print (arr_view)
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[5 6 7]
[ 0  1  2  3  4 50 50 50  8  9]
[50 50 50]
[100 100 100]
[ 0  1  2  3  4 50 50 50  8  9]


In [98]:
# using boolean arrays
arr = np.arange(0, 10)
print (arr)
print (arr > 5)
print (~(arr > 5))
print (arr[arr > 5])
print (True, not True, False, not False)
print (arr[~(arr > 5)])
arr[arr > 5] = 100
print (arr)

[0 1 2 3 4 5 6 7 8 9]
[False False False False False False  True  True  True  True]
[ True  True  True  True  True  True False False False False]
[6 7 8 9]
True False False True
[0 1 2 3 4 5]
[  0   1   2   3   4   5 100 100 100 100]


In [106]:
arr = np.arange(0, 10)
print (arr)
print ((arr > 3) & (arr < 8))
print (arr[(arr > 3) & (arr < 8)])
print ((arr < 3) | (arr > 8))
print (arr[(arr < 3) | (arr > 8)])

[0 1 2 3 4 5 6 7 8 9]
[False False False False  True  True  True  True False False]
[4 5 6 7]
[ True  True  True False False False False False False  True]
[0 1 2 9]


In [111]:
arr = np.arange(0, 10)
print (arr)
print (arr % 2 == 0)
print (arr[arr % 2 == 0])
print (arr[arr % 2 == 1])
print (arr[arr % 2 != 0])

[0 1 2 3 4 5 6 7 8 9]
[ True False  True False  True False  True False  True False]
[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5 7 9]


In [128]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob'])
print (names, type(names))
print (names == 'Bob')
print (names == 'bob')
print (names != 'Bob')
print (names[names != 'Bob'])
print ((names == 'Bob') | (names == 'Joe'))
print (names[(names == 'Bob') | (names == 'Joe')])
names[names == 'Bob'] = 'Tom'
print (names)

['Bob' 'Joe' 'Will' 'Bob'] <class 'numpy.ndarray'>
[ True False False  True]
[False False False False]
[False  True  True False]
['Joe' 'Will']
[ True  True False  True]
['Bob' 'Joe' 'Bob']
['Tom' 'Joe' 'Will' 'Tom']


In [129]:
names = np.array(['Bob', 'Joe', 'Will', 'Will', 'Joe', 'Bob', 'Bob'])
print (names, type(names))
print (np.unique(names))

['Bob' 'Joe' 'Will' 'Will' 'Joe' 'Bob' 'Bob'] <class 'numpy.ndarray'>
['Bob' 'Joe' 'Will']


### Vectorized Operations

In [135]:
nums = np.arange(10)
print (nums, type(nums))
print (list(nums), type(list(nums)), nums.tolist(), type(nums.tolist()))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9] <class 'list'>


In [158]:
import math
nums = np.arange(10)
print (nums, type(nums))
print (nums * 100)    # vector * scalar operation
print (nums * np.array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100]))    # vector * vector operation
print (np.sqrt(nums), math.sqrt(100), np.sqrt(100))     # Error !!! for math.sqrt(nums))
print (np.sqrt(nums))
print (np.ceil(np.sqrt(nums)))
print (np.floor(np.sqrt(nums)))
print (np.isnan(nums))
print (np.max(nums), np.min(nums))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>
[  0 100 200 300 400 500 600 700 800 900]
[  0 100 200 300 400 500 600 700 800 900]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 10.0 10.0
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[0. 1. 2. 2. 2. 3. 3. 3. 3. 3.]
[0. 1. 1. 1. 2. 2. 2. 2. 2. 3.]
[False False False False False False False False False False]
9 0


In [156]:
print (nums)
print ( np.array([1, -2, 3, -4, 20, -30, 40, -50, 13, 17]))
print (np.maximum(nums, np.array([1, -2, 3, -4, 20, -30, 40, -50, 13, 17])))
print (np.minimum(nums, np.array([1, -2, 3, -4, 20, -30, 40, -50, 13, 17])))

[0 1 2 3 4 5 6 7 8 9]
[  1  -2   3  -4  20 -30  40 -50  13  17]
[ 1  1  3  3 20  5 40  7 13 17]
[  0  -2   2  -4   4 -30   6 -50   8   9]


In [169]:
vect1 = np.random.randn(50000)   # normalized random numbers will have average = 0 and Std = 1
print (vect1, len(vect1))
print (np.average(vect1), np.std(vect1))

[ 0.41515476 -0.11063751  3.57295007 ...  0.07505316 -0.6435396
  0.07978869] 50000
0.004439011917603305 1.0020758725155923


### Calculating Euclidean Distance

In [175]:
vect1 = np.random.randn(10)
vect2 = np.random.randn(10)
print (vect1, type(vect1), len(vect1))
print (vect2, type(vect2), len(vect2))
dist = np.sqrt(np.sum((vect1 - vect2) ** 2))   # vector calculation
print ("Distance =", dist)

total = 0
for i in range(len(vect1)):
    total = total + (vect1[i] - vect2[i]) ** 2
dist = np.sqrt(total)
print ("Distance =", dist)

[ 0.65055851  0.68495882 -1.57808922  0.34574258  0.38115181 -0.8688066
 -0.69011693  1.32610491 -1.46265996  0.18664746] <class 'numpy.ndarray'> 10
[ 0.296259   -0.9086623  -0.5199586   0.43078684  1.05435631  0.89193248
  1.12429073  0.98027085  0.41616586 -0.03130062] <class 'numpy.ndarray'> 10
Distance = 3.7861061756941923
Distance = 3.7861061756941923


In [190]:
# maths and stats
rnd = np.random.randn(8).reshape(4, 2)
print (rnd)
rnd = np.random.randn(4, 2)
print (rnd)
print (rnd.mean(), rnd.sum(), rnd.max(), rnd.argmax(), rnd.min(), rnd.argmin(), rnd.std(), rnd.std() ** 2, rnd.var())

[[-0.49003053 -0.32270773]
 [-0.84067407  1.47821415]
 [-0.01162732 -0.36943817]
 [ 0.82999987  1.15535814]]
[[ 0.61270769 -0.11353193]
 [-0.00969383 -0.36866022]
 [-0.46105207 -0.05895912]
 [ 0.26109505  1.3030334 ]]
0.1456173699529323 1.1649389596234585 1.303033398625703 7 -0.4610520738652685 4 0.540460573315071 0.29209763130805527 0.2920976313080552


In [194]:
rnd = np.random.randn(8).reshape(4, 2)
print (rnd)
print (rnd.sum(axis = 0))   # sum of columns
print (rnd.sum(axis = 1))   # sum of rows

[[-0.82498137  0.43015498]
 [-0.50326973  1.3771093 ]
 [-0.48928261  1.52981492]
 [-0.86082323 -1.9083702 ]]
[-2.67835693  1.42870901]
[-0.39482639  0.87383957  1.04053232 -2.76919342]


In [198]:
rnd = np.random.randn(8).reshape(4, 2)
print (rnd)
print (rnd >= 0)
print ((rnd >= 0).sum())
print ((rnd >= 0).any())
print ((rnd >= 0).all())

[[-0.542229   -0.32890974]
 [-1.79864855  0.21035219]
 [-0.66759417  0.82866017]
 [-1.2664159   0.91229755]]
[[False False]
 [False  True]
 [False  True]
 [False  True]]
3
True
False


In [205]:
# reshape, transpose and flatten
nums = np.arange(32)
print (nums)
nums = np.arange(32).reshape(8, 4)
print (nums)
print (nums.flatten())
print (nums.T)   # transpose of a matrix
print (nums.T.flatten())

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31]
[[ 0  4  8 12 16 20 24 28]
 [ 1  5  9 13 17 21 25 29]
 [ 2  6 10 14 18 22 26 30]
 [ 3  7 11 15 19 23 27 31]]
[ 0  4  8 12 16 20 24 28  1  5  9 13 17 21 25 29  2  6 10 14 18 22 26 30
  3  7 11 15 19 23 27 31]


In [208]:
print (np.random.randn(10) * 100 + 400)

[423.24637727 237.25613798 280.87345665 130.88642907 361.45830419
 345.58741655 510.95846245 355.31541669 362.03919979 260.64785633]


In [236]:
np.random.seed(101)
print (np.random.randn(10))
print (np.random.randint(0, 10, 20))

[ 2.70684984  0.62813271  0.90796945  0.50382575  0.65111795 -0.31931804
 -0.84807698  0.60596535 -2.01816824  0.74012206]
[1 3 8 3 3 2 8 9 3 7 0 9 7 9 8 4 3 3 7 4]


In [240]:
print (np.random.randn(10))
print (np.random.randint(0, 10, 20))

[-1.26359946 -0.69623188 -1.14821996  1.60743482 -1.22686962  1.40553189
 -1.13720133 -0.53547812  2.14271732  1.6914524 ]
[4 9 1 6 7 8 0 0 8 7 0 6 7 7 4 3 9 8 1 2]


### Broadcasting

<img src = "NumpyBroadcasting.png" width = 500 height = 500>

In [243]:
a = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
b = np.array([  0,  1,  2])
print (a, a.shape)
print (b, b.shape)
c = a + b
print (c, c.shape)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] (4, 3)
[0 1 2] (3,)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] (4, 3)


In [244]:
a = np.array([ 0, 1, 2])
b = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
print (a, a.shape)
print (b, b.shape)
c= a+b
print(c,c.shape)

[0 1 2] (3,)
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] (4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] (4, 3)


In [246]:
a = np.array([0, 1, 2])
b = np.array([[ 0],
              [10],
              [20],
              [30]])
print (a, a.shape)
print (b, b.shape)
c = a + b
print(c, c.shape)

[0 1 2] (3,)
[[ 0]
 [10]
 [20]
 [30]] (4, 1)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] (4, 3)


In [247]:
a = np.array([[  0,  1,  2],
              [  0,  1,  2],
              [  0,  1,  2],
              [  0,  1,  2]])
b = np.array([[ 0,  0,  0],
              [10, 10, 10],
              [20, 20, 20],
              [30, 30, 30]])
print (a, a.shape)
print (b, b.shape)
c = a + b
print(c, c.shape)

[[0 1 2]
 [0 1 2]
 [0 1 2]
 [0 1 2]] (4, 3)
[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] (4, 3)
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]] (4, 3)
