## PANDAS: INTRODUCTION

### PANDAS: Data Manipulation

### Data Structures in Pandas

There are two different data structures are there in Pandas -
* **Series -** It is a one-dimensional labeled array capable of holding any data type (integer, string, floating point numbers, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** It is a 2-dimensional labeled data structure with columns of potentially different types. We can think of it is like an Excel spreadsheet or SQL table, or a Series of Objects.

### Series Data Structure

In [3]:
# importing required modules
import pandas as pd
import numpy as np

In [2]:
# creating an empty Series
s = pd.Series()
print (s, type(s))

Series([], dtype: float64) <class 'pandas.core.series.Series'>


<ipython-input-2-5b71265717c0>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [13]:
# create a Series from ndarray
data1 = np.array(['a', 'b', 'c', 'd', 'e'])
print (data1, type(data1))
s = pd.Series(data = data1)
print (s, type(s))

['a' 'b' 'c' 'd' 'e'] <class 'numpy.ndarray'>
0    a
1    b
2    c
3    d
4    e
dtype: object <class 'pandas.core.series.Series'>


In [11]:
data = np.array([100, 200, 300, 400])
print (data, type(data))
s = pd.Series(data, copy = False)
print (s, type(s))
s[0] = 999
print (s, type(s))
print (data, type(data))

[100 200 300 400] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
0    999
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
[999 200 300 400] <class 'numpy.ndarray'>


In [12]:
data = np.array([100, 200, 300, 400])
print (data, type(data))
s = pd.Series(data, copy = True)
print (s, type(s))
s[0] = 999
print (s, type(s))
print (data, type(data))

[100 200 300 400] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
0    999
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
[100 200 300 400] <class 'numpy.ndarray'>


In [29]:
data1 = np.array(['a', 'b', 'c', 'd', 'e'])
print (data1, type(data1))
s = pd.Series(data = data1, index = [100, 101, 102, 103, 104])
print (s, type(s))
print (s[101])
s = pd.Series(data = data1, index = [100, 101, 101, 103, 104])
print (s, type(s))
print (s[101])
print (s[104])

['a' 'b' 'c' 'd' 'e'] <class 'numpy.ndarray'>
100    a
101    b
102    c
103    d
104    e
dtype: object <class 'pandas.core.series.Series'>
b
100    a
101    b
101    c
103    d
104    e
dtype: object <class 'pandas.core.series.Series'>
101    b
101    c
dtype: object
e


In [22]:
# create a Series from dictionary
data = {'a':101., 'b':2345, 'c':221., 'd':30.}
print (data, type(data))
s = pd.Series(data)
print (s, type(s))

{'a': 101.0, 'b': 2345, 'c': 221.0, 'd': 30.0} <class 'dict'>
a     101.0
b    2345.0
c     221.0
d      30.0
dtype: float64 <class 'pandas.core.series.Series'>


In [41]:
data = {'a':101., 'b':2345, 'c':221., 'd':30.}
print (data, type(data))
s = pd.Series(data, index = ['b', 'b', 'a', 'd', 'c', 'c', 'b'])
print (s, type(s))
print (s['b'])
print (s[0])
print (s[6], s[3])

{'a': 101.0, 'b': 2345, 'c': 221.0, 'd': 30.0} <class 'dict'>
b    2345.0
b    2345.0
a     101.0
d      30.0
c     221.0
c     221.0
b    2345.0
dtype: float64 <class 'pandas.core.series.Series'>
b    2345.0
b    2345.0
b    2345.0
dtype: float64
2345.0
2345.0 30.0


In [40]:
# create Series from scalar
s = pd.Series(data = 5, index = [1, 3, 2, 4])
print (s, type(s))
print (s[1])

1    5
3    5
2    5
4    5
dtype: int64 <class 'pandas.core.series.Series'>
5


In [47]:
# create Series from a list
list1 = [11, 22, 33, 44, 55]
s = pd.Series(list1)
print (s)
print (s[2])   # indexing
s = pd.Series(data = list1, index = ['aa', 'bb', 'cc', 'dd', 'ee'])
print (s)
print (s['cc'], s[2])

0    11
1    22
2    33
3    44
4    55
dtype: int64
33
aa    11
bb    22
cc    33
dd    44
ee    55
dtype: int64
33 33


In [48]:
print (s)

aa    11
bb    22
cc    33
dd    44
ee    55
dtype: int64


In [56]:
print (s[:3])   # slicing
print (s[2:])
print (s[::-1])
print (s[1:3])
print (s[['bb', 'dd']])

aa    11
bb    22
cc    33
dtype: int64
cc    33
dd    44
ee    55
dtype: int64
ee    55
dd    44
cc    33
bb    22
aa    11
dtype: int64
bb    22
cc    33
dtype: int64
bb    22
dd    44
dtype: int64


### Data Frame Data Structure

### Create Data Frame

In [81]:
my_columns = ['name', 'age', 'gender', 'job']
user1 = pd.DataFrame([['alice', 19, 'F', 'student'], ['john', 26, 'M', 'student']], columns = my_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [82]:
my_columns = ['name', 'age', 'gender', 'job']
user2 = pd.DataFrame(data = [['eric', 22, 'M', 'student'], ['paul', 58, 'F', 'manager']], columns = my_columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [66]:
# my_dict = dict(name = ['peter', 'julie'], age = [33, 44], gender = ['M', 'F'], job = ['engineer', 'scientist'])
my_dict = {'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']}
print (my_dict, type(my_dict))
user3 = pd.DataFrame(data = my_dict)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

### Concatenation of the Data Frame

In [71]:
users = user1.append(user2, ignore_index = False)
users

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   58      F  manager

In [70]:
users = user1.append(user2, ignore_index = True)
users

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   58      F  manager

In [73]:
users = user1.append(user2, ignore_index = True).append(user3, ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [83]:
users = pd.concat([user1, user2, user3], ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

### Join DataFrame

In [95]:
my_dict = dict(name = ['alice', 'john', 'eric', 'julie', 'tom'], height = [165, 180, 175, 171, 181])
print (my_dict)
user4 = pd.DataFrame(data = my_dict)
user4

{'name': ['alice', 'john', 'eric', 'julie', 'tom'], 'height': [165, 180, 175, 171, 181]}


name  height
0  alice     165
1   john     180
2   eric     175
3  julie     171
4    tom     181

In [96]:
# inner join: all rows with common names
merge_inner = pd.merge(users, user4, on = "name", how = "inner")
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [98]:
# outer join: all rows with common and uncommon names
merge_outer = pd.merge(users, user4, on = "name", how = "outer")
merge_outer

name   age gender        job  height
0  alice  19.0      F    student   165.0
1   john  26.0      M    student   180.0
2   eric  22.0      M    student   175.0
3   paul  58.0      F    manager     NaN
4  peter  33.0      M   engineer     NaN
5  julie  44.0      F  scientist   171.0
6    tom   NaN    NaN        NaN   181.0

In [99]:
# left-outer join: all rows from left and matching from right
merge_left_outer = pd.merge(users, user4, on = "name", how = "left")
merge_left_outer

name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3   paul   58      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   171.0

In [100]:
# right-outer join: matching rows from left and all from right
merge_right_outer = pd.merge(users, user4, on = "name", how = "right")
merge_right_outer

name   age gender        job  height
0  alice  19.0      F    student     165
1   john  26.0      M    student     180
2   eric  22.0      M    student     175
3  julie  44.0      F  scientist     171
4    tom   NaN    NaN        NaN     181

### Summarizing

In [101]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [112]:
print (type(users))
users.head(3)

<class 'pandas.core.frame.DataFrame'>


name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [108]:
users.tail(3)

name  age gender        job
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [110]:
users.describe()

age
count   6.000000
mean   33.666667
std    14.895189
min    19.000000
25%    23.000000
50%    29.500000
75%    41.250000
max    58.000000

In [113]:
users.describe(include='all')

name        age gender      job
count       6   6.000000      6        6
unique      6        NaN      2        4
top     peter        NaN      M  student
freq        1        NaN      3        3
mean      NaN  33.666667    NaN      NaN
std       NaN  14.895189    NaN      NaN
min       NaN  19.000000    NaN      NaN
25%       NaN  23.000000    NaN      NaN
50%       NaN  29.500000    NaN      NaN
75%       NaN  41.250000    NaN      NaN
max       NaN  58.000000    NaN      NaN

In [114]:
users.describe(include=['object'])

name gender      job
count       6      6        6
unique      6      2        4
top     peter      M  student
freq        1      3        3

In [118]:
print (users.index)
print (users.columns)
users.dtypes

RangeIndex(start=0, stop=6, step=1)
Index(['name', 'age', 'gender', 'job'], dtype='object')


name      object
age        int64
gender    object
job       object
dtype: object

In [122]:
print (users.shape)
print (users.values)

(6, 4)
[['alice' 19 'F' 'student']
 ['john' 26 'M' 'student']
 ['eric' 22 'M' 'student']
 ['paul' 58 'F' 'manager']
 ['peter' 33 'M' 'engineer']
 ['julie' 44 'F' 'scientist']]


In [123]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    6 non-null      object
 1   age     6 non-null      int64 
 2   gender  6 non-null      object
 3   job     6 non-null      object
dtypes: int64(1), object(3)
memory usage: 320.0+ bytes


In [124]:
merge_outer

name   age gender        job  height
0  alice  19.0      F    student   165.0
1   john  26.0      M    student   180.0
2   eric  22.0      M    student   175.0
3   paul  58.0      F    manager     NaN
4  peter  33.0      M   engineer     NaN
5  julie  44.0      F  scientist   171.0
6    tom   NaN    NaN        NaN   181.0

In [125]:
merge_outer.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   name    7 non-null      object 
 1   age     6 non-null      float64
 2   gender  6 non-null      object 
 3   job     6 non-null      object 
 4   height  5 non-null      float64
dtypes: float64(2), object(3)
memory usage: 336.0+ bytes


### Columns selection

In [126]:
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [130]:
print (users['gender'])
print (type(users['gender']))

0    F
1    M
2    M
3    F
4    M
5    F
Name: gender, dtype: object
<class 'pandas.core.series.Series'>


In [133]:
print (users.gender)
print (type(users.gender))

0    F
1    M
2    M
3    F
4    M
5    F
Name: gender, dtype: object
<class 'pandas.core.series.Series'>


In [134]:
users[['gender', 'name']]

gender   name
0      F  alice
1      M   john
2      M   eric
3      F   paul
4      M  peter
5      F  julie

In [135]:
mycols = ['gender', 'name']
users[mycols]

gender   name
0      F  alice
1      M   john
2      M   eric
3      F   paul
4      M  peter
5      F  julie

### Rows Selection

In [138]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [140]:
df.iloc[2]

name         eric
age            22
gender          M
job       student
Name: 2, dtype: object

In [150]:
print (df.iloc[0][1], df.iloc[0]['age'], df.loc[0][1], df.loc[0]['age'])
print (df.iloc[0, 1], df.iloc[0]['age'], df.loc[0][1], df.loc[0, 'age'])

19 19 19 19
19 19 19 19


In [151]:
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [158]:
print (df.shape, df.shape[0], df.shape[1])
for i in range(df.shape[0]):
    row = df.iloc[i]
    row.age += 100
    df.iloc[i] = row
df

(6, 4) 6 4


C:\Users\Arnab\anaconda3\lib\site-packages\pandas\core\generic.py:5494: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self[name] = value


name  age gender        job
0  alice  119      F    student
1   john  126      M    student
2   eric  122      M    student
3   paul  158      F    manager
4  peter  133      M   engineer
5  julie  144      F  scientist

### Row selection and filtering

In [164]:
# simple logical filtering
print (users.age)
young_bool = users.age < 30
print (young_bool)
users[young_bool]

0    19
1    26
2    22
3    58
4    33
5    44
Name: age, dtype: int64
0     True
1     True
2     True
3    False
4    False
5    False
Name: age, dtype: bool


name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student

In [165]:
users[~young_bool]

name  age gender        job
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [166]:
users[~young_bool].job

3      manager
4     engineer
5    scientist
Name: job, dtype: object

In [168]:
users[~young_bool]['job']

3      manager
4     engineer
5    scientist
Name: job, dtype: object

In [167]:
users[~young_bool][['job', 'name']]

job   name
3    manager   paul
4   engineer  peter
5  scientist  julie

In [170]:
# advanced logical filtering
users[users.age < 30][['age', 'job', 'gender']]

age      job gender
0   19  student      F
1   26  student      M
2   22  student      M

In [171]:
users[(users.age < 30) & (users.gender == 'M')]

name  age gender      job
1  john   26      M  student
2  eric   22      M  student

In [172]:
users[(users.age < 30) & (users.gender == 'M')][['name', 'gender', 'age']]

name gender  age
1  john      M   26
2  eric      M   22

In [173]:
users[users.job.isin(['student', 'manager'])]

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   58      F  manager

### Sorting

In [175]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [180]:
print (df.age.sort_values())
print (df.age.sort_values(ascending=True))
print (df.age.sort_values(ascending=False))

0    19
2    22
1    26
4    33
5    44
3    58
Name: age, dtype: int64
0    19
2    22
1    26
4    33
5    44
3    58
Name: age, dtype: int64
3    58
5    44
4    33
1    26
2    22
0    19
Name: age, dtype: int64


In [181]:
df.sort_values(by = 'age')

name  age gender        job
0  alice   19      F    student
2   eric   22      M    student
1   john   26      M    student
4  peter   33      M   engineer
5  julie   44      F  scientist
3   paul   58      F    manager

In [182]:
df.sort_values(by = 'age', ascending=False)

name  age gender        job
3   paul   58      F    manager
5  julie   44      F  scientist
4  peter   33      M   engineer
1   john   26      M    student
2   eric   22      M    student
0  alice   19      F    student

In [184]:
df = df.sort_values(by = 'age', ascending=False)
df

name  age gender        job
3   paul   58      F    manager
5  julie   44      F  scientist
4  peter   33      M   engineer
1   john   26      M    student
2   eric   22      M    student
0  alice   19      F    student

In [185]:
df = users.copy()
df

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [186]:
df.sort_values(by = 'age', ascending = False, inplace = True)
df

name  age gender        job
3   paul   58      F    manager
5  julie   44      F  scientist
4  peter   33      M   engineer
1   john   26      M    student
2   eric   22      M    student
0  alice   19      F    student

In [187]:
df.sort_values(by = ['job', 'age'])

name  age gender        job
4  peter   33      M   engineer
3   paul   58      F    manager
5  julie   44      F  scientist
0  alice   19      F    student
2   eric   22      M    student
1   john   26      M    student

In [188]:
df.sort_values(by = ['gender', 'age'])

name  age gender        job
0  alice   19      F    student
5  julie   44      F  scientist
3   paul   58      F    manager
2   eric   22      M    student
1   john   26      M    student
4  peter   33      M   engineer

In [ ]:
### Reshaping by Pivoting