## PANDAS: INTRODUCTION

### PANDAS: Data Manipulation

### Data Structures in Pandas

There are two different data structures are there in Pandas -
* **Series -** It is a one-dimensional labeled array capable of holding any data type (integer, string, floating point numbers, Python objects etc.). The axis are collectively referred to as the index.
* **Data Frame -** It is a 2-dimensional labeled data structure with columns of potentially different types. We can think of it is like an Excel spreadsheet or SQL table, or a Series of Objects.

### Series Data Structure

In [3]:
# importing required modules
import pandas as pd
import numpy as np

In [2]:
# creating an empty Series
s = pd.Series()
print (s, type(s))

Series([], dtype: float64) <class 'pandas.core.series.Series'>


<ipython-input-2-5b71265717c0>:2: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.
  s = pd.Series()


In [13]:
# create a Series from ndarray
data1 = np.array(['a', 'b', 'c', 'd', 'e'])
print (data1, type(data1))
s = pd.Series(data = data1)
print (s, type(s))

['a' 'b' 'c' 'd' 'e'] <class 'numpy.ndarray'>
0    a
1    b
2    c
3    d
4    e
dtype: object <class 'pandas.core.series.Series'>


In [11]:
data = np.array([100, 200, 300, 400])
print (data, type(data))
s = pd.Series(data, copy = False)
print (s, type(s))
s[0] = 999
print (s, type(s))
print (data, type(data))

[100 200 300 400] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
0    999
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
[999 200 300 400] <class 'numpy.ndarray'>


In [12]:
data = np.array([100, 200, 300, 400])
print (data, type(data))
s = pd.Series(data, copy = True)
print (s, type(s))
s[0] = 999
print (s, type(s))
print (data, type(data))

[100 200 300 400] <class 'numpy.ndarray'>
0    100
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
0    999
1    200
2    300
3    400
dtype: int32 <class 'pandas.core.series.Series'>
[100 200 300 400] <class 'numpy.ndarray'>


In [29]:
data1 = np.array(['a', 'b', 'c', 'd', 'e'])
print (data1, type(data1))
s = pd.Series(data = data1, index = [100, 101, 102, 103, 104])
print (s, type(s))
print (s[101])
s = pd.Series(data = data1, index = [100, 101, 101, 103, 104])
print (s, type(s))
print (s[101])
print (s[104])

['a' 'b' 'c' 'd' 'e'] <class 'numpy.ndarray'>
100    a
101    b
102    c
103    d
104    e
dtype: object <class 'pandas.core.series.Series'>
b
100    a
101    b
101    c
103    d
104    e
dtype: object <class 'pandas.core.series.Series'>
101    b
101    c
dtype: object
e


In [22]:
# create a Series from dictionary
data = {'a':101., 'b':2345, 'c':221., 'd':30.}
print (data, type(data))
s = pd.Series(data)
print (s, type(s))

{'a': 101.0, 'b': 2345, 'c': 221.0, 'd': 30.0} <class 'dict'>
a     101.0
b    2345.0
c     221.0
d      30.0
dtype: float64 <class 'pandas.core.series.Series'>


In [41]:
data = {'a':101., 'b':2345, 'c':221., 'd':30.}
print (data, type(data))
s = pd.Series(data, index = ['b', 'b', 'a', 'd', 'c', 'c', 'b'])
print (s, type(s))
print (s['b'])
print (s[0])
print (s[6], s[3])

{'a': 101.0, 'b': 2345, 'c': 221.0, 'd': 30.0} <class 'dict'>
b    2345.0
b    2345.0
a     101.0
d      30.0
c     221.0
c     221.0
b    2345.0
dtype: float64 <class 'pandas.core.series.Series'>
b    2345.0
b    2345.0
b    2345.0
dtype: float64
2345.0
2345.0 30.0


In [40]:
# create Series from scalar
s = pd.Series(data = 5, index = [1, 3, 2, 4])
print (s, type(s))
print (s[1])

1    5
3    5
2    5
4    5
dtype: int64 <class 'pandas.core.series.Series'>
5


In [47]:
# create Series from a list
list1 = [11, 22, 33, 44, 55]
s = pd.Series(list1)
print (s)
print (s[2])   # indexing
s = pd.Series(data = list1, index = ['aa', 'bb', 'cc', 'dd', 'ee'])
print (s)
print (s['cc'], s[2])

0    11
1    22
2    33
3    44
4    55
dtype: int64
33
aa    11
bb    22
cc    33
dd    44
ee    55
dtype: int64
33 33


In [48]:
print (s)

aa    11
bb    22
cc    33
dd    44
ee    55
dtype: int64


In [56]:
print (s[:3])   # slicing
print (s[2:])
print (s[::-1])
print (s[1:3])
print (s[['bb', 'dd']])

aa    11
bb    22
cc    33
dtype: int64
cc    33
dd    44
ee    55
dtype: int64
ee    55
dd    44
cc    33
bb    22
aa    11
dtype: int64
bb    22
cc    33
dtype: int64
bb    22
dd    44
dtype: int64


### Data Frame Data Structure

### Create Data Frame

In [81]:
my_columns = ['name', 'age', 'gender', 'job']
user1 = pd.DataFrame([['alice', 19, 'F', 'student'], ['john', 26, 'M', 'student']], columns = my_columns)
user1

name  age gender      job
0  alice   19      F  student
1   john   26      M  student

In [82]:
my_columns = ['name', 'age', 'gender', 'job']
user2 = pd.DataFrame(data = [['eric', 22, 'M', 'student'], ['paul', 58, 'F', 'manager']], columns = my_columns)
user2

name  age gender      job
0  eric   22      M  student
1  paul   58      F  manager

In [66]:
# my_dict = dict(name = ['peter', 'julie'], age = [33, 44], gender = ['M', 'F'], job = ['engineer', 'scientist'])
my_dict = {'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']}
print (my_dict, type(my_dict))
user3 = pd.DataFrame(data = my_dict)
user3

{'name': ['peter', 'julie'], 'age': [33, 44], 'gender': ['M', 'F'], 'job': ['engineer', 'scientist']} <class 'dict'>


name  age gender        job
0  peter   33      M   engineer
1  julie   44      F  scientist

### Concatenation of the Data Frame

In [71]:
users = user1.append(user2, ignore_index = False)
users

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
0   eric   22      M  student
1   paul   58      F  manager

In [70]:
users = user1.append(user2, ignore_index = True)
users

name  age gender      job
0  alice   19      F  student
1   john   26      M  student
2   eric   22      M  student
3   paul   58      F  manager

In [73]:
users = user1.append(user2, ignore_index = True).append(user3, ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

In [83]:
users = pd.concat([user1, user2, user3], ignore_index = True)
users

name  age gender        job
0  alice   19      F    student
1   john   26      M    student
2   eric   22      M    student
3   paul   58      F    manager
4  peter   33      M   engineer
5  julie   44      F  scientist

### Join DataFrame

In [95]:
my_dict = dict(name = ['alice', 'john', 'eric', 'julie', 'tom'], height = [165, 180, 175, 171, 181])
print (my_dict)
user4 = pd.DataFrame(data = my_dict)
user4

{'name': ['alice', 'john', 'eric', 'julie', 'tom'], 'height': [165, 180, 175, 171, 181]}


name  height
0  alice     165
1   john     180
2   eric     175
3  julie     171
4    tom     181

In [96]:
# inner join: all rows with common names
merge_inner = pd.merge(users, user4, on = "name", how = "inner")
merge_inner

name  age gender        job  height
0  alice   19      F    student     165
1   john   26      M    student     180
2   eric   22      M    student     175
3  julie   44      F  scientist     171

In [98]:
# outer join: all rows with common and uncommon names
merge_outer = pd.merge(users, user4, on = "name", how = "outer")
merge_outer

name   age gender        job  height
0  alice  19.0      F    student   165.0
1   john  26.0      M    student   180.0
2   eric  22.0      M    student   175.0
3   paul  58.0      F    manager     NaN
4  peter  33.0      M   engineer     NaN
5  julie  44.0      F  scientist   171.0
6    tom   NaN    NaN        NaN   181.0

In [99]:
# left-outer join: all rows from left and matching from right
merge_left_outer = pd.merge(users, user4, on = "name", how = "left")
merge_left_outer

name  age gender        job  height
0  alice   19      F    student   165.0
1   john   26      M    student   180.0
2   eric   22      M    student   175.0
3   paul   58      F    manager     NaN
4  peter   33      M   engineer     NaN
5  julie   44      F  scientist   171.0

In [100]:
# right-outer join: matching rows from left and all from right
merge_right_outer = pd.merge(users, user4, on = "name", how = "right")
merge_right_outer

name   age gender        job  height
0  alice  19.0      F    student     165
1   john  26.0      M    student     180
2   eric  22.0      M    student     175
3  julie  44.0      F  scientist     171
4    tom   NaN    NaN        NaN     181